# Generated by Django 4.2.7 on 2023-12-18 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creator", models.CharField(max_length=255)),
                ("likes", models.IntegerField(default=0)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("map_title", models.CharField(max_length=100)),
                ("mobility", models.BooleanField(default=False)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Impossible", "impossible"),
                            ("Very Hard", "very_hard"),
                            ("Hard", "hard"),
                            ("Normal", "normal"),
                            ("Easy", "easy"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timer_status", models.BooleanField(default=False)),
                ("timer_duration", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "custom_game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="Game.customgame",
                    ),
                ),
            ],
        ),
    ]
