# Generated by Django 4.2.7 on 2023-12-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customgame",
            name="map_description",
            field=models.TextField(default="No description.", max_length=1000),
        ),
    ]
