# Generated by Django 4.2.7 on 2023-12-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Game", "0003_alter_customgame_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customgame",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
