# Generated by Django 4.2.7 on 2023-12-19 02:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("Game", "0004_alter_customgame_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customgame",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
