# Generated by Django 4.2.7 on 2023-12-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Game", "0005_alter_customgame_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customgame",
            name="dislikes",
            field=models.IntegerField(default=0),
        ),
    ]
